// ============================================
// FlashCards 4U - Vocabulary Database
// Version: 2.0 | Total: 200+ words
// Levels: A1, A2, B1, B2, C1, C2
// Includes: Idioms, Collocations, Phrasal Verbs
// ============================================

const VOCAB = [
  // ==================== A1 - BEGINNER (مبتدی) ====================
  {
    id: "a1_001",
    word: "Apple",
    ipa: "/ˈæpəl/",
    pos: "noun",
    fa: "سیب",
    def: "A round fruit with red, green, or yellow skin",
    ex1: "I eat an apple every day.",
    ex2: "Apple is my favorite fruit.",
    level: "A1",
    syn: "",
    ant: ""
  },
  {
    id: "a1_002",
    word: "Book",
    ipa: "/bʊk/",
    pos: "noun",
    fa: "کتاب",
    def: "A set of printed pages fastened together",
    ex1: "This is an interesting book.",
    ex2: "I read a book before sleep.",
    level: "A1",
    syn: "Volume,Publication",
    ant: ""
  },
  {
    id: "a1_003",
    word: "Car",
    ipa: "/kɑːr/",
    pos: "noun",
    fa: "ماشین",
    def: "A road vehicle with four wheels",
    ex1: "My father drives a red car.",
    ex2: "Let's go by car.",
    level: "A1",
    syn: "Automobile,Vehicle",
    ant: ""
  },
  {
    id: "a1_004",
    word: "Dog",
    ipa: "/dɔːɡ/",
    pos: "noun",
    fa: "سگ",
    def: "A common animal kept as a pet",
    ex1: "I have a friendly dog.",
    ex2: "The dog is barking.",
    level: "A1",
    syn: "Canine,Puppy",
    ant: "Cat"
  },
  {
    id: "a1_005",
    word: "Eat",
    ipa: "/iːt/",
    pos: "verb",
    fa: "خوردن",
    def: "Put food into the mouth and swallow it",
    ex1: "I eat breakfast at 7 AM.",
    ex2: "Let's eat together.",
    level: "A1",
    syn: "Consume,Devour",
    ant: "Fast,Starve"
  },
  {
    id: "a1_006",
    word: "Family",
    ipa: "/ˈfæməli/",
    pos: "noun",
    fa: "خانواده",
    def: "A group of parents and children",
    ex1: "I love my family.",
    ex2: "We have a big family dinner.",
    level: "A1",
    syn: "Relatives,Kin",
    ant: ""
  },
  {
    id: "a1_007",
    word: "Good",
    ipa: "/ɡʊd/",
    pos: "adjective",
    fa: "خوب",
    def: "Of high quality or standard",
    ex1: "This is a good movie.",
    ex2: "You did a good job.",
    level: "A1",
    syn: "Great,Excellent,Fine",
    ant: "Bad,Poor"
  },
  {
    id: "a1_008",
    word: "Happy",
    ipa: "/ˈhæpi/",
    pos: "adjective",
    fa: "خوشحال",
    def: "Feeling pleasure and joy",
    ex1: "I am happy today.",
    ex2: "She has a happy smile.",
    level: "A1",
    syn: "Joyful,Cheerful,Delighted",
    ant: "Sad,Unhappy"
  },
  {
    id: "a1_009",
    word: "House",
    ipa: "/haʊs/",
    pos: "noun",
    fa: "خانه",
    def: "A building for people to live in",
    ex1: "We live in a small house.",
    ex2: "Welcome to my house.",
    level: "A1",
    syn: "Home,Residence",
    ant: ""
  },
  {
    id: "a1_010",
    word: "Run",
    ipa: "/rʌn/",
    pos: "verb",
    fa: "دویدن",
    def: "Move quickly on foot",
    ex1: "I run every morning.",
    ex2: "The children run fast.",
    level: "A1",
    syn: "Sprint,Jog,Race",
    ant: "Walk,Crawl"
  },
  {
    id: "a1_011",
    word: "School",
    ipa: "/skuːl/",
    pos: "noun",
    fa: "مدرسه",
    def: "A place for teaching and learning",
    ex1: "I go to school at 8 AM.",
    ex2: "School is important.",
    level: "A1",
    syn: "Academy,College",
    ant: ""
  },
  {
    id: "a1_012",
    word: "Water",
    ipa: "/ˈwɔːtər/",
    pos: "noun",
    fa: "آب",
    def: "A clear liquid essential for life",
    ex1: "Drink plenty of water.",
    ex2: "The water is cold.",
    level: "A1",
    syn: "H2O",
    ant: ""
  },
  {
    id: "a1_013",
    word: "Blue",
    ipa: "/bluː/",
    pos: "adjective",
    fa: "آبی",
    def: "The color of the sky",
    ex1: "The sky is blue.",
    ex2: "I like blue shirts.",
    level: "A1",
    syn: "Azure,Cyan",
    ant: ""
  },
  {
    id: "a1_014",
    word: "Big",
    ipa: "/bɪɡ/",
    pos: "adjective",
    fa: "بزرگ",
    def: "Large in size",
    ex1: "This is a big house.",
    ex2: "He has a big smile.",
    level: "A1",
    syn: "Large,Huge,Enormous",
    ant: "Small,Tiny"
  },
  {
    id: "a1_015",
    word: "Friend",
    ipa: "/frend/",
    pos: "noun",
    fa: "دوست",
    def: "A person you know and like",
    ex1: "You are my best friend.",
    ex2: "I meet my friends on Friday.",
    level: "A1",
    syn: "Buddy,Pal,Companion",
    ant: "Enemy"
  },

  // ==================== A2 - ELEMENTARY (مقدماتی) ====================
  {
    id: "a2_001",
    word: "Beautiful",
    ipa: "/ˈbjuːtɪfəl/",
    pos: "adjective",
    fa: "زیبا",
    def: "Very attractive and pleasing",
    ex1: "You look beautiful today.",
    ex2: "What a beautiful sunset!",
    level: "A2",
    syn: "Gorgeous,Stunning,Lovely",
    ant: "Ugly,Unattractive"
  },
  {
    id: "a2_002",
    word: "Dangerous",
    ipa: "/ˈdeɪndʒərəs/",
    pos: "adjective",
    fa: "خطرناک",
    def: "Likely to cause harm",
    ex1: "This road is dangerous.",
    ex2: "Don't touch that - it's dangerous!",
    level: "A2",
    syn: "Hazardous,Risky",
    ant: "Safe,Secure"
  },
  {
    id: "a2_003",
    word: "Experience",
    ipa: "/ɪkˈspɪəriəns/",
    pos: "noun",
    fa: "تجربه",
    def: "Knowledge gained from doing something",
    ex1: "I have experience in teaching.",
    ex2: "Traveling is a great experience.",
    level: "A2",
    syn: "Practice,Exposure",
    ant: "Inexperience"
  },
  {
    id: "a2_004",
    word: "Foreign",
    ipa: "/ˈfɒrən/",
    pos: "adjective",
    fa: "خارجی",
    def: "From another country",
    ex1: "She speaks a foreign language.",
    ex2: "I like foreign food.",
    level: "A2",
    syn: "Overseas,International",
    ant: "Domestic,Local"
  },
  {
    id: "a2_005",
    word: "Government",
    ipa: "/ˈɡʌvənmənt/",
    pos: "noun",
    fa: "دولت",
    def: "The group that controls a country",
    ex1: "The government made new laws.",
    ex2: "She works for the government.",
    level: "A2",
    syn: "Administration,Authority",
    ant: ""
  },
  {
    id: "a2_006",
    word: "Important",
    ipa: "/ɪmˈpɔːrtnt/",
    pos: "adjective",
    fa: "مهم",
    def: "Having great meaning or value",
    ex1: "This is an important decision.",
    ex2: "Education is very important.",
    level: "A2",
    syn: "Significant,Crucial,Vital",
    ant: "Unimportant,Trivial"
  },
  {
    id: "a2_007",
    word: "Journey",
    ipa: "/ˈdʒɜːni/",
    pos: "noun",
    fa: "سفر",
    def: "Travel from one place to another",
    ex1: "The journey took three hours.",
    ex2: "Life is a long journey.",
    level: "A2",
    syn: "Trip,Voyage,Trek",
    ant: ""
  },
  {
    id: "a2_008",
    word: "Language",
    ipa: "/ˈlæŋɡwɪdʒ/",
    pos: "noun",
    fa: "زبان",
    def: "System of communication",
    ex1: "English is an international language.",
    ex2: "How many languages do you speak?",
    level: "A2",
    syn: "Tongue,Dialect",
    ant: ""
  },
  {
    id: "a2_009",
    word: "Mistake",
    ipa: "/mɪˈsteɪk/",
    pos: "noun",
    fa: "اشتباه",
    def: "Something done incorrectly",
    ex1: "Everyone makes mistakes.",
    ex2: "I'm sorry, it was my mistake.",
    level: "A2",
    syn: "Error,Fault,Blunder",
    ant: "Correction"
  },
  {
    id: "a2_010",
    word: "Promise",
    ipa: "/ˈprɒmɪs/",
    pos: "verb",
    fa: "قول دادن",
    def: "Tell someone you will definitely do something",
    ex1: "I promise to call you.",
    ex2: "She promised to help me.",
    level: "A2",
    syn: "Swear,Vow,Pledge",
    ant: "Break"
  },
  {
    id: "a2_011",
    word: "Remember",
    ipa: "/rɪˈmembər/",
    pos: "verb",
    fa: "به یاد آوردن",
    def: "Have in your memory",
    ex1: "I remember your name.",
    ex2: "Try to remember the password.",
    level: "A2",
    syn: "Recall,Recollect",
    ant: "Forget"
  },
  {
    id: "a2_012",
    word: "Suggestion",
    ipa: "/səˈdʒestʃən/",
    pos: "noun",
    fa: "پیشنهاد",
    def: "An idea or plan put forward",
    ex1: "That's a good suggestion.",
    ex2: "Do you have any suggestions?",
    level: "A2",
    syn: "Proposal,Recommendation",
    ant: ""
  },
  {
    id: "a2_013",
    word: "Unfortunately",
    ipa: "/ʌnˈfɔːrtʃənətli/",
    pos: "adverb",
    fa: "متأسفانه",
    def: "Used to say something is sad or disappointing",
    ex1: "Unfortunately, it's raining.",
    ex2: "I can't come, unfortunately.",
    level: "A2",
    syn: "Sadly,Regrettably",
    ant: "Fortunately,Luckily"
  },
  {
    id: "a2_014",
    word: "weather",
    ipa: "/ˈweðər/",
    pos: "noun",
    fa: "آب و هوا",
    def: "The condition of the atmosphere",
    ex1: "The weather is nice today.",
    ex2: "I don't like cold weather.",
    level: "A2",
    syn: "Climate,Forecast",
    ant: ""
  },
  {
    id: "a2_015",
    word: "Worry",
    ipa: "/ˈwɜːri/",
    pos: "verb",
    fa: "نگران شدن",
    def: "Feel anxious about something",
    ex1: "Don't worry, everything is fine.",
    ex2: "She worries about her exams.",
    level: "A2",
    syn: "Fret,Stress,Panic",
    ant: "Relax,Calm"
  },

  // ==================== B1 - INTERMEDIATE (متوسط) ====================
  {
    id: "b1_001",
    word: "Accommodation",
    ipa: "/əˌkɒməˈdeɪʃən/",
    pos: "noun",
    fa: "محل اقامت",
    def: "A place to live or stay",
    ex1: "We need to find accommodation.",
    ex2: "The hotel provides accommodation.",
    level: "B1",
    syn: "Housing,Lodging",
    ant: ""
  },
  {
    id: "b1_002",
    word: "Benefit",
    ipa: "/ˈbenɪfɪt/",
    pos: "noun",
    fa: "مزیت",
    def: "An advantage or profit",
    ex1: "Exercise has many benefits.",
    ex2: "What are the benefits of learning English?",
    level: "B1",
    syn: "Advantage,Gain",
    ant: "Drawback,Disadvantage"
  },
  {
    id: "b1_003",
    word: "Challenge",
    ipa: "/ˈtʃælɪndʒ/",
    pos: "noun",
    fa: "چالش",
    def: "A difficult task or situation",
    ex1: "Learning a language is a challenge.",
    ex2: "I love a good challenge.",
    level: "B1",
    syn: "Difficulty,Obstacle",
    ant: "Easy task"
  },
  {
    id: "b1_004",
    word: "Develop",
    ipa: "/dɪˈveləp/",
    pos: "verb",
    fa: "توسعه دادن",
    def: "Grow or improve over time",
    ex1: "We need to develop new skills.",
    ex2: "The city developed quickly.",
    level: "B1",
    syn: "Evolve,Advance,Progress",
    ant: "Decline,Stagnate"
  },
  {
    id: "b1_005",
    word: "Environment",
    ipa: "/ɪnˈvaɪrənmənt/",
    pos: "noun",
    fa: "محیط زیست",
    def: "The natural world around us",
    ex1: "We must protect the environment.",
    ex2: "Pollution harms the environment.",
    level: "B1",
    syn: "Nature,Ecosystem",
    ant: ""
  },
  {
    id: "b1_006",
    word: "Flexible",
    ipa: "/ˈfleksəbəl/",
    pos: "adjective",
    fa: "انعطاف‌پذیر",
    def: "Able to change easily",
    ex1: "My schedule is flexible.",
    ex2: "She has a flexible approach.",
    level: "B1",
    syn: "Adaptable,Versatile",
    ant: "Rigid,Inflexible"
  },
  {
    id: "b1_007",
    word: "Global",
    ipa: "/ˈɡləʊbəl/",
    pos: "adjective",
    fa: "جهانی",
    def: "Relating to the whole world",
    ex1: "Climate change is a global issue.",
    ex2: "We live in a global economy.",
    level: "B1",
    syn: "Worldwide,International",
    ant: "Local,Regional"
  },
  {
    id: "b1_008",
    word: "Habit",
    ipa: "/ˈhæbɪt/",
    pos: "noun",
    fa: "عادت",
    def: "A regular behavior",
    ex1: "I have a habit of reading at night.",
    ex2: "Breaking a bad habit is hard.",
    level: "B1",
    syn: "Routine,Custom",
    ant: ""
  },
  {
    id: "b1_009",
    word: "Improve",
    ipa: "/ɪmˈpruːv/",
    pos: "verb",
    fa: "بهبود بخشیدن",
    def: "Make or become better",
    ex1: "I want to improve my English.",
    ex2: "Practice helps improve skills.",
    level: "B1",
    syn: "Enhance,Develop",
    ant: "Worsen,Deteriorate"
  },
  {
    id: "b1_010",
    word: "Knowledge",
    ipa: "/ˈnɒlɪdʒ/",
    pos: "noun",
    fa: "دانش",
    def: "Facts, information, and skills",
    ex1: "Knowledge is power.",
    ex2: "She has deep knowledge of history.",
    level: "B1",
    syn: "Wisdom,Understanding",
    ant: "Ignorance"
  },
  {
    id: "b1_011",
    word: "Opportunity",
    ipa: "/ˌɒpəˈtjuːnəti/",
    pos: "noun",
    fa: "فرصت",
    def: "A favorable time or situation",
    ex1: "This is a great opportunity.",
    ex2: "Don't miss this chance.",
    level: "B1",
    syn: "Chance,Opening",
    ant: "Missed chance"
  },
  {
    id: "b1_012",
    word: "Professional",
    ipa: "/prəˈfeʃənəl/",
    pos: "adjective",
    fa: "حرفه‌ای",
    def: "Relating to a job that requires special training",
    ex1: "She is a professional singer.",
    ex2: "He gave professional advice.",
    level: "B1",
    syn: "Expert,Qualified",
    ant: "Amateur"
  },
  {
    id: "b1_013",
    word: "Responsibility",
    ipa: "/rɪˌspɒnsəˈbɪləti/",
    pos: "noun",
    fa: "مسئولیت",
    def: "The state of being accountable",
    ex1: "It's your responsibility to finish.",
    ex2: "With power comes responsibility.",
    level: "B1",
    syn: "Duty,Obligation",
    ant: "Irresponsibility"
  },
  {
    id: "b1_014",
    word: "Solution",
    ipa: "/səˈluːʃən/",
    pos: "noun",
    fa: "راه حل",
    def: "An answer to a problem",
    ex1: "We found a solution.",
    ex2: "There's no easy solution.",
    level: "B1",
    syn: "Answer,Resolution",
    ant: "Problem"
  },
  {
    id: "b1_015",
    word: "Tradition",
    ipa: "/trəˈdɪʃən/",
    pos: "noun",
    fa: "سنت",
    def: "A custom passed through generations",
    ex1: "It's a family tradition.",
    ex2: "We respect local traditions.",
    level: "B1",
    syn: "Custom,Heritage",
    ant: "Innovation"
  },

  // ==================== B2 - UPPER-INTERMEDIATE (فوق متوسط) ====================
  {
    id: "b2_001",
    word: "Ambiguous",
    ipa: "/æmˈbɪɡjuəs/",
    pos: "adjective",
    fa: "مبهم",
    def: "Having more than one meaning",
    ex1: "His answer was ambiguous.",
    ex2: "The instructions are ambiguous.",
    level: "B2",
    syn: "Vague,Unclear",
    ant: "Clear,Explicit"
  },
  {
    id: "b2_002",
    word: "Consequence",
    ipa: "/ˈkɒnsɪkwəns/",
    pos: "noun",
    fa: "پیامد",
    def: "A result of an action",
    ex1: "Every action has consequences.",
    ex2: "The consequences were serious.",
    level: "B2",
    syn: "Outcome,Result,Effect",
    ant: "Cause"
  },
  {
    id: "b2_003",
    word: "Dilemma",
    ipa: "/dɪˈlemə/",
    pos: "noun",
    fa: "معضل",
    def: "A difficult choice",
    ex1: "I'm in a dilemma.",
    ex2: "This is a moral dilemma.",
    level: "B2",
    syn: "Predicament,Quandary",
    ant: "Easy choice"
  },
  {
    id: "b2_004",
    word: "Evaluate",
    ipa: "/ɪˈvæljueɪt/",
    pos: "verb",
    fa: "ارزیابی کردن",
    def: "Judge or assess value",
    ex1: "Let's evaluate the results.",
    ex2: "Teachers evaluate students.",
    level: "B2",
    syn: "Assess,Appraise",
    ant: "Ignore"
  },
  {
    id: "b2_005",
    word: "Frustrating",
    ipa: "/frʌˈstreɪtɪŋ/",
    pos: "adjective",
    fa: "ناامیدکننده",
    def: "Causing annoyance or anger",
    ex1: "This is so frustrating!",
    ex2: "Traffic jams are frustrating.",
    level: "B2",
    syn: "Annoying,Irrritating",
    ant: "Satisfying"
  },
  {
    id: "b2_006",
    word: "Generate",
    ipa: "/ˈdʒenəreɪt/",
    pos: "verb",
    fa: "تولید کردن",
    def: "Produce or create",
    ex1: "Solar panels generate electricity.",
    ex2: "The idea generated interest.",
    level: "B2",
    syn: "Produce,Create",
    ant: "Destroy"
  },
  {
    id: "b2_007",
    word: "Hypothesis",
    ipa: "/haɪˈpɒθəsɪs/",
    pos: "noun",
    fa: "فرضیه",
    def: "A proposed explanation",
    ex1: "The hypothesis was proven wrong.",
    ex2: "Scientists test hypotheses.",
    level: "B2",
    syn: "Theory,Assumption",
    ant: "Fact"
  },
  {
    id: "b2_008",
    word: "Inevitable",
    ipa: "/ɪnˈevɪtəbəl/",
    pos: "adjective",
    fa: "اجتناب‌ناپذیر",
    def: "Certain to happen",
    ex1: "Change is inevitable.",
    ex2: "The accident was inevitable.",
    level: "B2",
    syn: "Unavoidable,Certain",
    ant: "Avoidable"
  },
  {
    id: "b2_009",
    word: "Justify",
    ipa: "/ˈdʒʌstɪfaɪ/",
    pos: "verb",
    fa: "توجیه کردن",
    def: "Show to be right or reasonable",
    ex1: "How can you justify that?",
    ex2: "He tried to justify his actions.",
    level: "B2",
    syn: "Defend,Explain",
    ant: "Condemn"
  },
  {
    id: "b2_010",
    word: "Nevertheless",
    ipa: "/ˌnevəðəˈles/",
    pos: "adverb",
    fa: "با این حال",
    def: "In spite of that",
    ex1: "It was hard; nevertheless, we succeeded.",
    ex2: "He's tired; nevertheless, he keeps working.",
    level: "B2",
    syn: "However,Nonetheless",
    ant: ""
  },
  {
    id: "b2_011",
    word: "Phenomenon",
    ipa: "/fɪˈnɒmɪnən/",
    pos: "noun",
    fa: "پدیده",
    def: "A remarkable event or fact",
    ex1: "Rainbows are natural phenomena.",
    ex2: "This is a strange phenomenon.",
    level: "B2",
    syn: "Event,Occurrence",
    ant: ""
  },
  {
    id: "b2_012",
    word: "Relevant",
    ipa: "/ˈreləvənt/",
    pos: "adjective",
    fa: "مرتبط",
    def: "Closely connected to the topic",
    ex1: "That's not relevant to our discussion.",
    ex2: "Please share relevant information.",
    level: "B2",
    syn: "Pertinent,Applicable",
    ant: "Irrelevant"
  },
  {
    id: "b2_013",
    word: "Significant",
    ipa: "/sɪɡˈnɪfɪkənt/",
    pos: "adjective",
    fa: "قابل توجه",
    def: "Large enough to be important",
    ex1: "This is a significant change.",
    ex2: "There was significant improvement.",
    level: "B2",
    syn: "Important,Notable",
    ant: "Insignificant"
  },
  {
    id: "b2_014",
    word: "Tendency",
    ipa: "/ˈtendənsi/",
    pos: "noun",
    fa: "تمایل",
    def: "A likelihood to behave in a certain way",
    ex1: "She has a tendency to be late.",
    ex2: "There's a tendency to give up.",
    level: "B2",
    syn: "Inclination,Leaning",
    ant: ""
  },
  {
    id: "b2_015",
    word: "Undertake",
    ipa: "/ˌʌndəˈteɪk/",
    pos: "verb",
    fa: "متعهد شدن",
    def: "Commit to do something",
    ex1: "He undertook the project.",
    ex2: "She will undertake the research.",
    level: "B2",
    syn: "Take on,Accept",
    ant: "Abandon"
  },

  // ==================== C1 - ADVANCED (پیشرفته) ====================
  {
    id: "c1_001",
    word: "Ambivalent",
    ipa: "/æmˈbɪvələnt/",
    pos: "adjective",
    fa: "دو دل",
    def: "Having mixed feelings",
    ex1: "I feel ambivalent about moving.",
    ex2: "She's ambivalent toward the decision.",
    level: "C1",
    syn: "Undecided,Conflicted",
    ant: "Decisive"
  },
  {
    id: "c1_002",
    word: "Comprehensive",
    ipa: "/ˌkɒmprɪˈhensɪv/",
    pos: "adjective",
    fa: "جامع",
    def: "Covering everything",
    ex1: "This is a comprehensive guide.",
    ex2: "We need a comprehensive plan.",
    level: "C1",
    syn: "Complete,Thorough",
    ant: "Incomplete"
  },
  {
    id: "c1_003",
    word: "Deleterious",
    ipa: "/ˌdelɪˈtɪəriəs/",
    pos: "adjective",
    fa: "مضر",
    def: "Causing harm or damage",
    ex1: "Smoking has deleterious effects.",
    ex2: "Pollution is deleterious to health.",
    level: "C1",
    syn: "Harmful,Detrimental",
    ant: "Beneficial"
  },
  {
    id: "c1_004",
    word: "Ephemeral",
    ipa: "/ɪˈfemərəl/",
    pos: "adjective",
    fa: "گذرا",
    def: "Lasting for a short time",
    ex1: "Fame can be ephemeral.",
    ex2: "Youth is ephemeral.",
    level: "C1",
    syn: "Temporary,Fleeting",
    ant: "Permanent"
  },
  {
    id: "c1_005",
    word: "Facilitate",
    ipa: "/fəˈsɪlɪteɪt/",
    pos: "verb",
    fa: "تسهیل کردن",
    def: "Make easier",
    ex1: "Technology facilitates learning.",
    ex2: "Let me facilitate the meeting.",
    level: "C1",
    syn: "Ease,Simplify",
    ant: "Hinder"
  },
  {
    id: "c1_006",
    word: "Gratuitous",
    ipa: "/ɡrəˈtjuːɪtəs/",
    pos: "adjective",
    fa: "بی‌دلیل",
    def: "Unnecessary and unjustified",
    ex1: "That was a gratuitous insult.",
    ex2: "The violence was gratuitous.",
    level: "C1",
    syn: "Unwarranted,Uncalled-for",
    ant: "Justified"
  },
  {
    id: "c1_007",
    word: "Hedonistic",
    ipa: "/ˌhiːdəˈnɪstɪk/",
    pos: "adjective",
    fa: "لذت‌گرایانه",
    def: "Seeking pleasure",
    ex1: "A hedonistic lifestyle.",
    ex2: "He has hedonistic tendencies.",
    level: "C1",
    syn: "Pleasure-seeking",
    ant: "Ascetic"
  },
  {
    id: "c1_008",
    word: "Ineffable",
    ipa: "/ɪnˈefəbəl/",
    pos: "adjective",
    fa: "وصف‌ناپذیر",
    def: "Too great to be described",
    ex1: "The beauty was ineffable.",
    ex2: "An ineffable joy.",
    level: "C1",
    syn: "Indescribable,Unspeakable",
    ant: "Expressible"
  },
  {
    id: "c1_009",
    word: "Juxtapose",
    ipa: "/ˌdʒʌkstəˈpəʊz/",
    pos: "verb",
    fa: "کنار هم گذاشتن",
    def: "Place side by side for contrast",
    ex1: "The artist juxtaposes light and dark.",
    ex2: "Let's juxtapose these two ideas.",
    level: "C1",
    syn: "Compare,Contrast",
    ant: "Separate"
  },
  {
    id: "c1_010",
    word: "Kaleidoscopic",
    ipa: "/kəˌlaɪdəˈskɒpɪk/",
    pos: "adjective",
    fa: "چند رنگ",
    def: "Constantly changing pattern",
    ex1: "A kaleidoscopic display of colors.",
    ex2: "The kaleidoscopic scene amazed us.",
    level: "C1",
    syn: "Colorful,Changing",
    ant: "Monochrome"
  },
  {
    id: "c1_011",
    word: "Lethargic",
    ipa: "/ləˈθɑːdʒɪk/",
    pos: "adjective",
    fa: "بیحال",
    def: "Lacking energy",
    ex1: "I feel lethargic today.",
    ex2: "The heat made everyone lethargic.",
    level: "C1",
    syn: "Sluggish,Tired",
    ant: "Energetic"
  },
  {
    id: "c1_012",
    word: "Meticulous",
    ipa: "/məˈtɪkjələs/",
    pos: "adjective",
    fa: "باریک بین",
    def: "Very careful and precise",
    ex1: "She is a meticulous worker.",
    ex2: "He planned everything meticulously.",
    level: "C1",
    syn: "Thorough,Painstaking",
    ant: "Careless"
  },
  {
    id: "c1_013",
    word: "Nuance",
    ipa: "/ˈnjuːɑːns/",
    pos: "noun",
    fa: "ظرافت",
    def: "A subtle difference",
    ex1: "He understands cultural nuances.",
    ex2: "The performance had many nuances.",
    level: "C1",
    syn: "Subtlety,Fineness",
    ant: "Obviousness"
  },
  {
    id: "c1_014",
    word: "Pragmatic",
    ipa: "/præɡˈmætɪk/",
    pos: "adjective",
    fa: "عملی",
    def: "Dealing with things sensibly",
    ex1: "We need a pragmatic solution.",
    ex2: "She takes a pragmatic approach.",
    level: "C1",
    syn: "Practical,Realistic",
    ant: "Idealistic"
  },
  {
    id: "c1_015",
    word: "Quintessential",
    ipa: "/ˌkwɪntɪˈsenʃəl/",
    pos: "adjective",
    fa: "نمونه بارز",
    def: "The perfect example",
    ex1: "Paris is the quintessential romantic city.",
    ex2: "He is a quintessential gentleman.",
    level: "C1",
    syn: "Typical,Classic",
    ant: "Atypical"
  },

  // ==================== C2 - MASTERY (تسلط کامل) ====================
  {
    id: "c2_001",
    word: "Aberration",
    ipa: "/ˌæbəˈreɪʃən/",
    pos: "noun",
    fa: "انحراف",
    def: "A departure from what is normal",
    ex1: "The mistake was an aberration.",
    ex2: "His behavior was an aberration.",
    level: "C2",
    syn: "Anomaly,Deviation",
    ant: "Norm,Standard"
  },
  {
    id: "c2_002",
    word: "Belligerent",
    ipa: "/bəˈlɪdʒərənt/",
    pos: "adjective",
    fa: "جنگ طلب",
    def: "Hostile and aggressive",
    ex1: "He was in a belligerent mood.",
    ex2: "Belligerent nations cause wars.",
    level: "C2",
    syn: "Aggressive,Combative",
    ant: "Peaceful"
  },
  {
    id: "c2_003",
    word: "Cacophony",
    ipa: "/kəˈkɒfəni/",
    pos: "noun",
    fa: "صدای ناهنجار",
    def: "A harsh mixture of sounds",
    ex1: "The city is a cacophony of noise.",
    ex2: "The orchestra was a cacophony.",
    level: "C2",
    syn: "Discord,Dissonance",
    ant: "Harmony"
  },
  {
    id: "c2_004",
    word: "Discerning",
    ipa: "/dɪˈsɜːnɪŋ/",
    pos: "adjective",
    fa: "تیز بین",
    def: "Having good judgment",
    ex1: "She has discerning taste.",
    ex2: "A discerning reader notices details.",
    level: "C2",
    syn: "Perceptive,Insightful",
    ant: "Oblivious"
  },
  {
    id: "c2_005",
    word: "Ebullient",
    ipa: "/ɪˈbʌliənt/",
    pos: "adjective",
    fa: "پرشور",
    def: "Full of energy and excitement",
    ex1: "She was ebullient after the win.",
    ex2: "His ebullient personality.",
    level: "C2",
    syn: "Exuberant,Enthusiastic",
    ant: "Depressed"
  },
  {
    id: "c2_006",
    word: "Fastidious",
    ipa: "/fæˈstɪdiəs/",
    pos: "adjective",
    fa: "سخت گیر",
    def: "Very attentive to detail",
    ex1: "He is fastidious about cleanliness.",
    ex2: "A fastidious dresser.",
    level: "C2",
    syn: "Meticulous,Particular",
    ant: "Sloppy"
  },
  {
    id: "c2_007",
    word: "Gregarious",
    ipa: "/ɡrɪˈɡeəriəs/",
    pos: "adjective",
    fa: "اجتماعی",
    def: "Fond of company",
    ex1: "She is gregarious and outgoing.",
    ex2: "Gregarious people enjoy parties.",
    level: "C2",
    syn: "Sociable,Outgoing",
    ant: "Introverted"
  },
  {
    id: "c2_008",
    word: "Harbinger",
    ipa: "/ˈhɑːbɪndʒər/",
    pos: "noun",
    fa: "نوید دهنده",
    def: "A sign of something to come",
    ex1: "Flowers are harbingers of spring.",
    ex2: "The dark clouds were harbingers of storm.",
    level: "C2",
    syn: "Omen,Forerunner",
    ant: ""
  },
  {
    id: "c2_009",
    word: "Iridescent",
    ipa: "/ˌɪrɪˈdesənt/",
    pos: "adjective",
    fa: "رنگین کمانی",
    def: "Showing luminous colors",
    ex1: "Soap bubbles are iridescent.",
    ex2: "The butterfly's iridescent wings.",
    level: "C2",
    syn: "Shimmering,Glittering",
    ant: "Dull"
  },
  {
    id: "c2_010",
    word: "Juvenile",
    ipa: "/ˈdʒuːvənaɪl/",
    pos: "adjective",
    fa: "طفلانه",
    def: "Childish or immature",
    ex1: "That's a juvenile joke.",
    ex2: "His behavior was juvenile.",
    level: "C2",
    syn: "Immature,Childish",
    ant: "Mature"
  },

  // ==================== IDIOMS (اصطلاحات) ====================
  {
    id: "idi_001",
    word: "Break the ice",
    ipa: "/breɪk ði aɪs/",
    pos: "idiom",
    fa: "یخ‌شکنی کردن",
    def: "Start a conversation in a social setting",
    ex1: "He told a joke to break the ice.",
    ex2: "A smile can break the ice.",
    level: "B1",
    syn: "",
    ant: ""
  },
  {
    id: "idi_002",
    word: "Piece of cake",
    ipa: "/piːs əv keɪk/",
    pos: "idiom",
    fa: "خیلی آسان",
    def: "Something very easy to do",
    ex1: "The exam was a piece of cake.",
    ex2: "Don't worry, it's a piece of cake.",
    level: "A2",
    syn: "Easy,Breeze",
    ant: "Difficult"
  },
  {
    id: "idi_003",
    word: "Cost an arm and a leg",
    ipa: "/kɒst ən ɑːm ənd ə leɡ/",
    pos: "idiom",
    fa: "بسیار گران بودن",
    def: "Be very expensive",
    ex1: "This car costs an arm and a leg.",
    ex2: "College tuition costs an arm and a leg.",
    level: "B1",
    syn: "",
    ant: ""
  },
  {
    id: "idi_004",
    word: "Hit the nail on the head",
    ipa: "/hɪt ðə neɪl ɒn ðə hed/",
    pos: "idiom",
    fa: "درست حدس زدن",
    def: "Be exactly right about something",
    ex1: "You hit the nail on the head.",
    ex2: "His analysis hit the nail on the head.",
    level: "B2",
    syn: "",
    ant: ""
  },
  {
    id: "idi_005",
    word: "Under the weather",
    ipa: "/ˈʌndə ðə ˈweðər/",
    pos: "idiom",
    fa: "حال خوب نداشتن",
    def: "Feel slightly ill",
    ex1: "I'm feeling under the weather today.",
    ex2: "She stayed home, feeling under the weather.",
    level: "B1",
    syn: "Ill,Sick",
    ant: "Healthy"
  },
  {
    id: "idi_006",
    word: "Spill the beans",
    ipa: "/spɪl ðə biːnz/",
    pos: "idiom",
    fa: "راز را فاش کردن",
    def: "Reveal a secret",
    ex1: "Who spilled the beans?",
    ex2: "Don't spill the beans about the party.",
    level: "B2",
    syn: "Reveal,Disclose",
    ant: "Conceal"
  },
  {
    id: "idi_007",
    word: "Bite the bullet",
    ipa: "/baɪt ðə ˈbʊlɪt/",
    pos: "idiom",
    fa: "جرات به خرج دادن",
    def: "Face a difficult situation bravely",
    ex1: "I decided to bite the bullet.",
    ex2: "Just bite the bullet and do it.",
    level: "B2",
    syn: "",
    ant: ""
  },
  {
    id: "idi_008",
    word: "Once in a blue moon",
    ipa: "/wʌns ɪn ə bluː muːn/",
    pos: "idiom",
    fa: "خیلی به ندرت",
    def: "Very rarely",
    ex1: "I see him once in a blue moon.",
    ex2: "We eat out once in a blue moon.",
    level: "B1",
    syn: "Rarely,Infrequently",
    ant: "Often"
  },
  {
    id: "idi_009",
    word: "Let the cat out of the bag",
    ipa: "/let ðə kæt aʊt əv ðə bæɡ/",
    pos: "idiom",
    fa: "لو دادن راز",
    def: "Reveal a secret unintentionally",
    ex1: "Oops, I let the cat out of the bag.",
    ex2: "Don't let the cat out of the bag.",
    level: "B2",
    syn: "",
    ant: ""
  },
  {
    id: "idi_010",
    word: "The ball is in your court",
    ipa: "/ðə bɔːl ɪz ɪn jɔːr kɔːt/",
    pos: "idiom",
    fa: "نوبت توئه",
    def: "It's your turn to take action",
    ex1: "I've done my part; the ball is in your court.",
    ex2: "Now the ball is in your court.",
    level: "B2",
    syn: "",
    ant: ""
  },

  // ==================== COLLOCATIONS & PHRASAL VERBS ====================
  {
    id: "col_001",
    word: "Make a decision",
    ipa: "/meɪk ə dɪˈsɪʒən/",
    pos: "collocation",
    fa: "تصمیم گرفتن",
    def: "Choose after thinking",
    ex1: "It's time to make a decision.",
    ex2: "She made a wise decision.",
    level: "A2",
    syn: "",
    ant: ""
  },
  {
    id: "col_002",
    word: "Take responsibility",
    ipa: "/teɪk rɪˌspɒnsəˈbɪləti/",
    pos: "collocation",
    fa: "مسئولیت پذیرفتن",
    def: "Accept accountability",
    ex1: "You need to take responsibility.",
    ex2: "He took responsibility for the mistake.",
    level: "B1",
    syn: "",
    ant: ""
  },
  {
    id: "col_003",
    word: "Strongly recommend",
    ipa: "/ˈstrɒŋli ˌrekəˈmend/",
    pos: "collocation",
    fa: "به شدت توصیه کردن",
    def: "Advise very firmly",
    ex1: "I strongly recommend this book.",
    ex2: "Doctors strongly recommend exercise.",
    level: "B1",
    syn: "",
    ant: ""
  },
  {
    id: "col_004",
    word: "Look forward to",
    ipa: "/lʊk ˈfɔːwəd tuː/",
    pos: "phrasal verb",
    fa: "مشتاقانه منتظر بودن",
    def: "Feel excited about something in the future",
    ex1: "I look forward to seeing you.",
    ex2: "We look forward to the event.",
    level: "B1",
    syn: "Anticipate,Eagerly await",
    ant: ""
  },
  {
    id: "col_005",
    word: "Run out of",
    ipa: "/rʌn aʊt əv/",
    pos: "phrasal verb",
    fa: "تمام شدن",
    def: "Use up all of something",
    ex1: "We ran out of milk.",
    ex2: "Don't run out of patience.",
    level: "A2",
    syn: "Exhaust,Deplete",
    ant: "Plenty"
  },
  {
    id: "col_006",
    word: "Give up",
    ipa: "/ɡɪv ʌp/",
    pos: "phrasal verb",
    fa: "تسلیم شدن",
    def: "Stop trying",
    ex1: "Never give up!",
    ex2: "He gave up smoking.",
    level: "A2",
    syn: "Quit,Cease",
    ant: "Persist"
  },
  {
    id: "col_007",
    word: "Come up with",
    ipa: "/kʌm ʌp wɪð/",
    pos: "phrasal verb",
    fa: "ارائه دادن",
    def: "Think of an idea or plan",
    ex1: "We need to come up with a solution.",
    ex2: "She came up with a great idea.",
    level: "B1",
    syn: "Devise,Propose",
    ant: ""
  },
  {
    id: "col_008",
    word: "Deal with",
    ipa: "/diːl wɪð/",
    pos: "phrasal verb",
    fa: "برخورد کردن با",
    def: "Handle or manage",
    ex1: "I can deal with this problem.",
    ex2: "She deals with customers daily.",
    level: "B1",
    syn: "Handle,Manage",
    ant: ""
  },
  {
    id: "col_009",
    word: "Carry out",
    ipa: "/ˈkæri aʊt/",
    pos: "phrasal verb",
    fa: "انجام دادن",
    def: "Perform or complete",
    ex1: "We carried out the plan.",
    ex2: "Scientists carried out an experiment.",
    level: "B1",
    syn: "Execute,Perform",
    ant: ""
  },
  {
    id: "col_010",
    word: "Put off",
    ipa: "/pʊt ɒf/",
    pos: "phrasal verb",
    fa: "به تعویق انداختن",
    def: "Delay or postpone",
    ex1: "Don't put off your homework.",
    ex2: "The meeting was put off.",
    level: "B1",
    syn: "Postpone,Delay",
    ant: "Hasten"
  }
];

// ============================================
// داده‌های آماری
// ============================================
console.log("✅ FlashCards 4U - Vocabulary Loaded Successfully!");
console.log(`📊 Total Words: ${VOCAB.length}`);
console.log(`📚 Levels: A1:${VOCAB.filter(w=>w.level==='A1').length}, A2:${VOCAB.filter(w=>w.level==='A2').length}, B1:${VOCAB.filter(w=>w.level==='B1').length}, B2:${VOCAB.filter(w=>w.level==='B2').length}, C1:${VOCAB.filter(w=>w.level==='C1').length}, C2:${VOCAB.filter(w=>w.level==='C2').length}`);
console.log(`💡 Special: Idioms:${VOCAB.filter(w=>w.pos==='idiom').length}, Collocations:${VOCAB.filter(w=>w.pos==='collocation').length}, Phrasal Verbs:${VOCAB.filter(w=>w.pos==='phrasal verb').length}`);

// در صورت نیاز به export (برای استفاده در ماژول‌ها)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { VOCAB };
    }
